theme: jekyll-theme-slate
title: "Arjailer"
description: "I'm a C# coder by profession and I occasionally do some side-projects, some of the more interesting of which are listed below"
show_downloads: false
